// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulifySystem.Repository.DBContext;

#nullable disable

namespace SchedulifySystem.Repository.Migrations
{
    [DbContext(typeof(SchedulifyContext))]
    [Migration("20250418062211_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsChangeDefaultPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmSchoolManager")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.ClassPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DateOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RoomCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("StartAt")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassScheduleId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ClassPeriod", (string)null);
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("SchoolScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StudentClassId")
                        .HasColumnType("int");

                    b.Property<string>("StudentClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolScheduleId");

                    b.HasIndex("StudentClassId");

                    b.ToTable("ClassSchedule", (string)null);
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurriculumCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurriculumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.CurriculumDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDoublePeriod")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecialized")
                        .HasColumnType("bit");

                    b.Property<int>("MainMinimumCouple")
                        .HasColumnType("int");

                    b.Property<int>("MainSlotPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("SlotPerTerm")
                        .HasColumnType("int");

                    b.Property<int>("SubMinimumCouple")
                        .HasColumnType("int");

                    b.Property<int>("SubSlotPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectInGroupType")
                        .HasColumnType("int");

                    b.Property<int?>("TermId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TermId");

                    b.ToTable("CurriculumDetail", (string)null);
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MeetingDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("NotificationURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.OTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isUsed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.PeriodChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassPeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsChangeForever")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("StartAt")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassPeriodId");

                    b.ToTable("PeriodChange");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.RoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleAssignment", (string)null);
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailabilityeStatus")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxClassPerTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoomCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.RoomSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Model")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("RoomSubjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomSubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int?>("Session")
                        .HasColumnType("int");

                    b.Property<int?>("SlotPerWeek")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("TermId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TermId");

                    b.ToTable("RoomSubjects");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.SchoolSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndWeek")
                        .HasColumnType("int");

                    b.Property<int>("FitnessPoint")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("StartWeek")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("TermId");

                    b.ToTable("SchoolSchedules");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolYearCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SchoolYears");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.StudentClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int?>("HomeroomTeacherId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("bit");

                    b.Property<int>("MainSession")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PeriodCount")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentClassGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HomeroomTeacherId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("StudentClassGroupId");

                    b.ToTable("StudentClasses");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.StudentClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("GroupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<string>("StudentClassGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("StudentClassGroups");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.StudentClassRoomSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoomSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("StudentClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomSubjectId");

                    b.HasIndex("StudentClassId");

                    b.ToTable("StudentClassRoomSubject");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeachedByHomeroomTeacher")
                        .HasColumnType("bit");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int?>("SlotSpecialized")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectGroupType")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalSlotInYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.SubmitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachedFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcess")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SubmitsRequests");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.TeachableSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppropriateLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeachableSubjects");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AvatarURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PeriodCount")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeacherRole")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.TeacherAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PeriodCount")
                        .HasColumnType("int");

                    b.Property<int?>("RoomSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("StudentClassId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomSubjectId");

                    b.HasIndex("StudentClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TermId");

                    b.ToTable("TeacherAssignments");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.TeacherUnavailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartAt")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherUnavailabilities");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartWeek")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Account", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("Accounts")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Building", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("Buildings")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.ClassPeriod", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.ClassSchedule", "ClassSchedule")
                        .WithMany("ClassPeriods")
                        .HasForeignKey("ClassScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Room", "Room")
                        .WithMany("ClassPeriods")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Subject", "Subject")
                        .WithMany("ClassPeriods")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Teacher", "Teacher")
                        .WithMany("ClassPeriods")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClassSchedule");

                    b.Navigation("Room");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.ClassSchedule", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.SchoolSchedule", "SchoolSchedule")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("SchoolScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.StudentClass", "StudentClass")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("StudentClassId");

                    b.Navigation("SchoolSchedule");

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Curriculum", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("Curriculums")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.SchoolYear", "SchoolYear")
                        .WithMany("Curriculums")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.CurriculumDetail", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Curriculum", "Curriculum")
                        .WithMany("CurriculumDetails")
                        .HasForeignKey("CurriculumId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Subject", "Subject")
                        .WithMany("CurriculumDetails")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Term", "Term")
                        .WithMany("CurriculumDetails")
                        .HasForeignKey("TermId");

                    b.Navigation("Curriculum");

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Department", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("Departments")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.District", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Notification", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.OTP", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Account", "Account")
                        .WithMany("OTPs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.PeriodChange", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.ClassPeriod", "ClassPeriod")
                        .WithMany("PeriodChanges")
                        .HasForeignKey("ClassPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassPeriod");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.RoleAssignment", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Account", "Account")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Department", "Department")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Role", "Role")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Room", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.RoomSubject", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Room", "Room")
                        .WithMany("RoomSubjects")
                        .HasForeignKey("RoomId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("RoomSubjects")
                        .HasForeignKey("SchoolId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Subject", "Subject")
                        .WithMany("RoomSubjects")
                        .HasForeignKey("SubjectId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Teacher", "Teacher")
                        .WithMany("RoomSubjects")
                        .HasForeignKey("TeacherId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Term", "Term")
                        .WithMany("RoomSubjects")
                        .HasForeignKey("TermId");

                    b.Navigation("Room");

                    b.Navigation("School");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.School", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Province", "Province")
                        .WithMany("Schools")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.SchoolSchedule", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("SchoolSchedules")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.SchoolYear", "SchoolYear")
                        .WithMany("SchoolSchedules")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Term", "Term")
                        .WithMany("SchoolSchedules")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("SchoolYear");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.StudentClass", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Teacher", "Teacher")
                        .WithMany("StudentClasses")
                        .HasForeignKey("HomeroomTeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Room", "Room")
                        .WithMany("StudentClasses")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("StudentClasses")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.SchoolYear", "SchoolYear")
                        .WithMany("StudentClasses")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.StudentClassGroup", "StudentClassGroup")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentClassGroupId");

                    b.Navigation("Room");

                    b.Navigation("School");

                    b.Navigation("SchoolYear");

                    b.Navigation("StudentClassGroup");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.StudentClassGroup", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Curriculum", "Curriculum")
                        .WithMany("StudentClassGroups")
                        .HasForeignKey("CurriculumId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("StudentClassGroups")
                        .HasForeignKey("SchoolId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.SchoolYear", "SchoolYear")
                        .WithMany("StudentClassGroups")
                        .HasForeignKey("SchoolYearId");

                    b.Navigation("Curriculum");

                    b.Navigation("School");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.StudentClassRoomSubject", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.RoomSubject", "RoomSubject")
                        .WithMany("StudentClassRoomSubjects")
                        .HasForeignKey("RoomSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.StudentClass", "StudentClass")
                        .WithMany("StudentClassRoomSubjects")
                        .HasForeignKey("StudentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomSubject");

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Subject", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.SchoolYear", "SchoolYear")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.SubmitRequest", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.SchoolYear", "SchoolYear")
                        .WithMany("SubmitRequests")
                        .HasForeignKey("SchoolYearId");

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Teacher", "Teacher")
                        .WithMany("SubmitRequests")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.TeachableSubject", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Subject", "Subject")
                        .WithMany("TeachableSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Teacher", "Teacher")
                        .WithMany("TeachableSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Teacher", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.TeacherAssignment", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.RoomSubject", "RoomSubject")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("RoomSubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SchedulifySystem.Repository.EntityModels.StudentClass", "StudentClass")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("StudentClassId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Subject", "Subject")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Teacher", "Teacher")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SchedulifySystem.Repository.EntityModels.Term", "Term")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomSubject");

                    b.Navigation("StudentClass");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.TeacherUnavailability", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.Teacher", "Teacher")
                        .WithMany("TeacherUnavailabilities")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Term", b =>
                {
                    b.HasOne("SchedulifySystem.Repository.EntityModels.SchoolYear", "SchoolYear")
                        .WithMany("Terms")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Account", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("OTPs");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.ClassPeriod", b =>
                {
                    b.Navigation("PeriodChanges");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.ClassSchedule", b =>
                {
                    b.Navigation("ClassPeriods");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Curriculum", b =>
                {
                    b.Navigation("CurriculumDetails");

                    b.Navigation("StudentClassGroups");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Department", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Province", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Role", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Room", b =>
                {
                    b.Navigation("ClassPeriods");

                    b.Navigation("RoomSubjects");

                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.RoomSubject", b =>
                {
                    b.Navigation("StudentClassRoomSubjects");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.School", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Buildings");

                    b.Navigation("Curriculums");

                    b.Navigation("Departments");

                    b.Navigation("RoomSubjects");

                    b.Navigation("SchoolSchedules");

                    b.Navigation("StudentClassGroups");

                    b.Navigation("StudentClasses");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.SchoolSchedule", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.SchoolYear", b =>
                {
                    b.Navigation("Curriculums");

                    b.Navigation("SchoolSchedules");

                    b.Navigation("StudentClassGroups");

                    b.Navigation("StudentClasses");

                    b.Navigation("Subjects");

                    b.Navigation("SubmitRequests");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.StudentClass", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("StudentClassRoomSubjects");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.StudentClassGroup", b =>
                {
                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Subject", b =>
                {
                    b.Navigation("ClassPeriods");

                    b.Navigation("CurriculumDetails");

                    b.Navigation("RoomSubjects");

                    b.Navigation("TeachableSubjects");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Teacher", b =>
                {
                    b.Navigation("ClassPeriods");

                    b.Navigation("RoomSubjects");

                    b.Navigation("StudentClasses");

                    b.Navigation("SubmitRequests");

                    b.Navigation("TeachableSubjects");

                    b.Navigation("TeacherAssignments");

                    b.Navigation("TeacherUnavailabilities");
                });

            modelBuilder.Entity("SchedulifySystem.Repository.EntityModels.Term", b =>
                {
                    b.Navigation("CurriculumDetails");

                    b.Navigation("RoomSubjects");

                    b.Navigation("SchoolSchedules");

                    b.Navigation("TeacherAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
